# 入力補完
[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
  source ~/.config/nvim/plugins/deoplete.vim
'''

# Ruby用入力補完
[[plugins]]
repo = 'osyo-manga/vim-monster'
on_i = 1
hook_add = '''
  source ~/.config/nvim/plugins/vim-monster.vim
'''

# slim用シンタックスハイライト
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']
